version: 1.0.{build}
image: Visual Studio 2019

install:
  - docker version

build_script:
  - docker build -t christianlr/mibarberschedule .

test_script:
  - docker run christianlr/mibarberschedule
